### ISSUE TITLE
compile failed on OSX 10.13.3

### ISSUE THREAD

**Issue by johnjohnsp1** [nezza/SDQAnalyzer#1]
Hello,
following the instruction I get this error:

╰─ python3 build_analyzer.py
Running on Darwin
g++ -I"./AnalyzerSDK/include" -O3 -w -c -fpic -o"release/SDQAnalyzer.o" "source/SDQAnalyzer.cpp"
source/SDQAnalyzer.cpp:74:7: error: call to 'abs' is ambiguous
                        if(std::abs(time_seconds - RESET_TIME) < MATCH_PRECISION)
                           ^~~~~~~~
/usr/include/stdlib.h:137:6: note: candidate function
int      abs(int) __pure2;
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:115:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:117:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
source/SDQAnalyzer.cpp:81:14: error: call to 'abs' is ambiguous
                        } else if(std::abs(time_seconds - FALSE_TIME) < MATCH_PRECISION)
                                  ^~~~~~~~
/usr/include/stdlib.h:137:6: note: candidate function
int      abs(int) __pure2;
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:115:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:117:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
source/SDQAnalyzer.cpp:87:14: error: call to 'abs' is ambiguous
                        } else if(std::abs(time_seconds - TRUE_TIME) < MATCH_PRECISION) {
                                  ^~~~~~~~
/usr/include/stdlib.h:137:6: note: candidate function
int      abs(int) __pure2;
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:115:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:117:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
3 errors generated.
Traceback (most recent call last):
  File "build_analyzer.py", line 76, in <module>
    run_command(release_command)
  File "build_analyzer.py", line 53, in run_command
    raise Exception("Shell execution returned nonzero status")
Exception: Shell execution returned nonzero status

any ideas ?
thanks

**Comment by nezza** [comment]
Hello and thanks for your report,

I just fixed this on master, also found another issue with the Saleae build script. For me this now builds on OSX, please let me know if it works for you!

**Comment by johnjohnsp1** [comment]
thanks for the reply, I can confirm it is now working good and compile works:

╰─ python3 build_analyzer.py
Running on Darwin
g++ -I"./AnalyzerSDK/include" -O3 -w -c -fpic -o"release/SDQAnalyzer.o" "source/SDQAnalyzer.cpp"
g++ -I"./AnalyzerSDK/include" -O0 -w -c -fpic -g -o"debug/SDQAnalyzer.o" "source/SDQAnalyzer.cpp"
g++ -I"./AnalyzerSDK/include" -O3 -w -c -fpic -o"release/SDQAnalyzerResults.o" "source/SDQAnalyzerResults.cpp"
g++ -I"./AnalyzerSDK/include" -O0 -w -c -fpic -g -o"debug/SDQAnalyzerResults.o" "source/SDQAnalyzerResults.cpp"
g++ -I"./AnalyzerSDK/include" -O3 -w -c -fpic -o"release/SDQAnalyzerSettings.o" "source/SDQAnalyzerSettings.cpp"
g++ -I"./AnalyzerSDK/include" -O0 -w -c -fpic -g -o"debug/SDQAnalyzerSettings.o" "source/SDQAnalyzerSettings.cpp"
g++ -I"./AnalyzerSDK/include" -O3 -w -c -fpic -o"release/SDQSimulationDataGenerator.o" "source/SDQSimulationDataGenerator.cpp"
g++ -I"./AnalyzerSDK/include" -O0 -w -c -fpic -g -o"debug/SDQSimulationDataGenerator.o" "source/SDQSimulationDataGenerator.cpp"
g++ -L"./AnalyzerSDK/lib" -lAnalyzer -dynamiclib -o release/libSDQAnalyzer.dylib release/SDQAnalyzer.o release/SDQAnalyzerResults.o release/SDQAnalyzerSettings.o release/SDQSimulationDataGenerator.o
g++ -L"./AnalyzerSDK/lib" -lAnalyzer -dynamiclib -o debug/libSDQAnalyzer.dylib debug/SDQAnalyzer.o debug/SDQAnalyzerResults.o debug/SDQAnalyzerSettings.o debug/SDQSimulationDataGenerator.o

Thanks

**Comment by nezza** [comment]
Perfect, thanks! Let me know if you run into any other issues!
