### ISSUE TITLE
is you code suppoert win10

### ISSUE THREAD

**Issue by wanming2008** [nezza/SDQAnalyzer#3]
is you code suppoert win10? thank you very much

**Comment by nezza** [comment]
Have you tried compiling it? What's the error message you are getting?

**Comment by wanming2008** [comment]
hi nezza

thanks for your answer

the error is ：

error：	MSB8036	The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".	SDQAnalyzer	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets	46	
![image](https://user-images.githubusercontent.com/4623260/69111148-9bf46700-0ab7-11ea-81aa-d7a1c620056b.png)

**Comment by wanming2008** [comment]
my sdk seems window sdk 10.0
![image](https://user-images.githubusercontent.com/4623260/69111283-102f0a80-0ab8-11ea-8ac7-0ccc494e1a89.png)

**Comment by wanming2008** [comment]
hi nezza

thanks for your answer
i find the way to success.
your code work very well


https://social.msdn.microsoft.com/Forums/en-US/7547f68d-6447-45cc-8eef-b652318ce9d2/visual-studio-2019-community-vctoolsinstalldir-property-not-defined?forum=visualstudiogeneral


![image](https://user-images.githubusercontent.com/4623260/69114443-4e302c80-0ac0-11ea-90c0-473af3ffb7a2.png)
