### ISSUE TITLE
Update analyzer to automatically build binaries using github actions

### ISSUE THREAD

**Issue by nbanerje** [nezza/SDQAnalyzer#5]
Hi! I'm a Product Manager at Saleae and we’ve made improvements to our analyzer build process. Specifically, we cleaned up the build system, and switched to cmake, so there aren't multiple project files anymore. By implementing the changes outlined [here](https://github.com/saleae/SampleAnalyzer/#updating-an-existing-analyzer-to-use-cmake--github-actions) you will be able to provide the community automatic builds in addition to a simplified build system. Let us know if you think you can make the changes or if you’d like us to make the changes for you. 

Additionally, if you would like to update your analyzer so that results appear in Logic 2’s data table you can follow the steps outlined [here](https://support.saleae.com/saleae-api-and-sdk/protocol-analyzer-sdk/framev2-hla-support-analyzer-sdk). Note that if you upgrade your analyzer to FrameV2 it will not be backward compatible with Logic 1.

We really appreciate your time and effort! Please let us know if you have any feedback or questions. Thanks!

**Comment by nezza** [comment]
Updated to Logic2 and also merged in your changes for Github actions - much appreciated, thanks a lot!
