### ISSUE TITLE
Implement tihmstars changes

### ISSUE THREAD

**Issue by arag0re** [nezza/SDQAnalyzer#7]
Hey there, your analyzer doesnt work anymore with the current version of logic2.
User [tihmstar](https://github.com/tihmstar/) fixed it in a fork.
But pull requests are locked for non collaborators. Please merge in the changes.
Thanks.
Repo is [here](https://github.com/tihmstar/SDQAnalyzer/)

**Comment by nezza** [comment]
Thanks for the note! I'm trying to figure out how to enable outside collaborators and then will jump on it

**Comment by arag0re** [comment]
Perfect thx
